sudo: required
services:
  - docker

before_install:
  - docker build -t sportnoi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sportnoi/react-test npm test

after_success:
  - docker build -t sportnoi/multi-client ./client
  - docker build -t sportnoi/multi-nginx ./nginx
  - docker build -t sportnoi/mulit-server ./server
  - docker build -t sportnoi/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push tem to docker hub
  - docker push sportnoi/multi-client
  - docker push sportnoi/multi-nginx
  - docker push sportnoi/multi-server
  - docker push sportnoi/multi-worker